apiVersion: v1
kind: Service
metadata:
  name: transaction-risk-service
spec:
  selector:
    app: transaction-risk
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
