name: CI Pipeline

on:
  push:           # run on pushes to any branch
  workflow_dispatch:

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Java runtime
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. Run unit tests
      - name: Run unit tests
        run: mvn test

      # 4. Build application JAR
      - name: Build JAR
        run: mvn clean package -DskipTests

      # 5. Initialize CodeQL (SAST)
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      # 6. Build project FOR CodeQL (MANDATORY FOR JAVA)
      - name: Build for CodeQL
        run: mvn clean compile

      # 7. Perform CodeQL analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      # 8. Build Docker image
      - name: Build Docker image
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/transaction-risk-service:latest
          docker build -t "${IMAGE}" .

      # 9. Scan Docker image with Trivy
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/transaction-risk-service:latest
          format: table
          exit-code: 1
          vuln-type: os,library
          severity: CRITICAL,HIGH

      # 10. Runtime smoke test
      - name: Run container for smoke test
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/transaction-risk-service:latest
          docker run -d -p 8080:8080 --name risk-app "${IMAGE}"
          sleep 15
          curl -f http://localhost:8080/actuator/health
          docker stop risk-app || true
          docker rm risk-app || true

      # 11. Login to DockerHub
      - name: DockerHub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 12. Push image to DockerHub
      - name: Push Docker image
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/transaction-risk-service:latest
          docker push "${IMAGE}"